---
services:
  console_backupper:
    container_name: console_backupper
    build: ./
    ports:
      - 8080:8080
    volumes:
      - "/tmp/console_backupper:/var/lib/console_backupper"
      - "./config.yml:/etc/console_backupper/config.yml:ro"
    develop:
      watch:

        - path: ./*.go
          action: rebuild
